# Generated by Django 3.2.5 on 2021-07-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productpromotion',
            name='date',
            field=models.DateField(),
        ),
    ]
