# Generated by Django 3.2.5 on 2021-07-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_report', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='product_id',
            new_name='product',
        ),
    ]
